<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_ClientController.php" was generated by ProBot AI.
* Date: 4/4/2023 2:50:10 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Client;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class ClientController extends Controller{
	public function index(){

		

		$clients = Client::paginate(5);
		return view("pages.erp.client.index",["clients"=>$clients]);
	}
	public function create(){

		

		return view("pages.erp.client.create",[]);
	}
	public function store(Request $request){

		
		//Client::create($request->all());
		$client = new Client;
		$client->name=$request->name;
		$client->mobile=$request->mobile;
		$client->email=$request->email;
		$client->description=$request->description;
date_default_timezone_set("Asia/Dhaka");
		$client->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$client->updated_at=date('Y-m-d H:i:s');

		$client->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		


		$client = Client::find($id);
		return view("pages.erp.client.show",["client"=>$client]);
	}
	public function edit(Client $client){

		
		return view("pages.erp.client.edit",["client"=>$client,]);
	}
	public function update(Request $request,Client $client){

		
		//Client::update($request->all());
		$client = Client::find($client->id);
		$client->name=$request->name;
		$client->mobile=$request->mobile;
		$client->email=$request->email;
		$client->description=$request->description;
date_default_timezone_set("Asia/Dhaka");
		$client->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$client->updated_at=date('Y-m-d H:i:s');

		$client->save();

		return redirect()->route("clients.index")->with('success','Updated Successfully.');
	}
	public function destroy(Client $client){
		

		$client->delete();
		return redirect()->route("clients.index")->with('success', 'Deleted Successfully.');
	}
}
?>
