<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_EmployeeController.php" was generated by ProBot AI.
* Date: 4/3/2023 7:45:38 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Department;
use App\Models\Employee;
use App\Models\Designation;
use App\Models\EmployeeDesignation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class EmployeeController extends Controller{
	public function index(){

		

		$employees = Employee::paginate(5);
		return view("pages.erp.employee.index",["employees"=>$employees]);
	}
	public function create(){
		
		return view("pages.erp.employee.create",["designations"=>EmployeeDesignation::all(),"departments"=>Department::all()]);
	}
	public function store(Request $request){

		
		//Employee::create($request->all());
		$employee = new Employee;
		$employee->name=$request->name;
		$employee->mobile=$request->mobile;
		$employee->email=$request->email;
		$employee->address=$request->address;
		$employee->salary=$request->salary;
		$employee->account_no=$request->account;		
		$employee->designation_id=$request->designation_id;
		$employee->department_id=$request->department_id;
		$employee->house_rent=$request->txHouserent;
		$employee->medicale_allowance=$request->txtMedicale;
		$employee->transport_allowance=$request->txtTransport;
		$employee->provident_fund=$request->txtProvident;
		$employee->income_tax=$request->txtIncome;
		$employee->insurance=$request->txtInsurance;


date_default_timezone_set("Asia/Dhaka");
		$employee->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$employee->updated_at=date('Y-m-d H:i:s');

		$employee->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		
		$employees=DB::table("employees as e")

        ->join("employee_designations as d","e.designation_id","=","d.id")
		->join("departments as s","e.department_id","=","s.id")
		->where('e.id', $id)
        ->select("e.id","e.name","e.mobile","e.email","e.address","d.name as desig","s.name as department","e.house_rent","e.medicale_allowance","e.transport_allowance","e.provident_fund","e.income_tax","e.insurance","e.created_at","e.updated_at")
		->first();
		return view("pages.erp.employee.show",["employee"=>$employees]);
	}
	public function edit(Employee $employee){
		
		return view("pages.erp.employee.edit",["employee"=>$employee,"designations"=>EmployeeDesignation::all(),"departments"=>Department::all()]);
	}
	public function update(Request $request,Employee $employee){
		
		//Employee::update($request->all());
		$employee = Employee::find($employee->id);
		$employee->name=$request->name;
		$employee->mobile=$request->mobile;
		$employee->email=$request->email;
		$employee->address=$request->address;
		$employee->salary=$request->salary;
		$employee->account_no=$request->account;

		$employee->designation_id=$request->designation_id;
		$employee->department_id=$request->department_id;
		$employee->house_rent=$request->txHouserent;
		$employee->medicale_allowance=$request->txtMedicale;
		$employee->transport_allowance=$request->txtTransport;
		$employee->provident_fund=$request->txtProvident;
		$employee->income_tax=$request->txtIncome;
		$employee->insurance=$request->txtInsurance;

date_default_timezone_set("Asia/Dhaka");
		$employee->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$employee->updated_at=date('Y-m-d H:i:s');

		$employee->save();

		return redirect()->route("employees.index")->with('success','Updated Successfully.');
	}
	public function destroy(Employee $employee){
		
		$employee->delete();
		return redirect()->route("employees.index")->with('success', 'Deleted Successfully.');
	}

	public function get_employee_json(){
        $id=$_GET["id"];     
        $request=Employee::find($id);
		
         return json_encode($request);
     }

}
?>
