<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_MaterialController.php" was generated by ProBot AI.
* Date: 4/6/2023 12:30:46 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Material;
use App\Models\Category;
use App\Models\Uom;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class MaterialController extends Controller{
	public function index(){

		

		$materials=DB::table("materials as m")

        ->join("categories as c","m.category_id","=","c.id")
		->join("uoms as u","m.uom_id","=","u.id")
		
        ->select("m.id","m.name","m.price","c.name as category","m.is_brand","u.name as uom","m.created_at","m.updated_at")		
        
		->paginate(5);

		return view("pages.erp.material.index",["materials"=>$materials]);
	}
	public function create(){

		
		return view("pages.erp.material.create",["categories"=>Category::all(),"uoms"=>Uom::all()]);
	}
	public function store(Request $request){

		$sess_id=session('sess_id');
   if(isset($sess_id))return redirect('/');
		//Material::create($request->all());
		$material = new Material;
		$material->name=$request->name;
		$material->price=$request->price;
		$material->category_id=$request->category_id;
		$material->is_brand=$request->is_brand;
		$material->uom_id=$request->uom_id;
date_default_timezone_set("Asia/Dhaka");
		$material->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$material->updated_at=date('Y-m-d H:i:s');

		$material->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		
		$material=DB::table("materials as m")

        ->join("categories as c","m.category_id","=","c.id")
		->join("uoms as u","m.uom_id","=","u.id")
		->where("m.id",$id)
        ->select("m.id","m.name","m.price","c.name as category","m.is_brand","u.name as uom","m.created_at","m.updated_at")		
        ->first();
		return view("pages.erp.material.show",["material"=>$material]);
	}
	public function edit(Material $material){

		
		return view("pages.erp.material.edit",["material"=>$material,"categories"=>Category::all(),"uom"=>Uom::all()]);
	}
	public function update(Request $request,Material $material){

		
		//Material::update($request->all());
		$material = Material::find($material->id);
		$material->name=$request->name;
		$material->price=$request->price;
		$material->category_id=$request->category_id;
		$material->is_brand=$request->is_brand;
		$material->uom_id=$request->uom_id;
date_default_timezone_set("Asia/Dhaka");
		$material->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$material->updated_at=date('Y-m-d H:i:s');

		$material->save();

		return redirect()->route("materials.index")->with('success','Updated Successfully.');
	}
	public function destroy(Material $material){
		
		$material->delete();
		return redirect()->route("materials.index")->with('success', 'Deleted Successfully.');
	}

	public function get_material_json(){
		
		$id=$_GET["id"];
		$request=Material::find($id);
		// $request=DB::table("materials as m")
		// ->join("uoms as u","m.uom_id","=","u.id")
		// ->where("m.id",$id)
		// ->select("m.*","u.name as uname")
		// ->get();
		return json_encode($request);

	}
}
?>
