<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_OwnerController.php" was generated by ProBot AI.
* Date: 4/5/2023 2:43:25 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Owner;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class OwnerController extends Controller{
	public function index(){
		
		$owners = Owner::paginate(10);
		return view("pages.erp.owner.index",["owners"=>$owners]);
	}
	public function create(){
		
		return view("pages.erp.owner.create",[]);
	}
	public function store(Request $request){
		
		//Owner::create($request->all());
		$owner = new Owner;
		$owner->name=$request->name;
		$owner->mobile=$request->mobile;
		$owner->email=$request->email;
		$owner->address=$request->address;
		if(isset($request->photo)){
			$owner->photo=$request->photo;
		}
date_default_timezone_set("Asia/Dhaka");
		$owner->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$owner->updated_at=date('Y-m-d H:i:s');

		$owner->save();
		if(isset($request->photo)){
			$imageName=$owner->id.'.'.$request->photo->extension();
			$owner->photo=$imageName;
			$owner->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		
		$owner = Owner::find($id);
		return view("pages.erp.owner.show",["owner"=>$owner]);
	}
	public function edit(Owner $owner){
		
		return view("pages.erp.owner.edit",["owner"=>$owner,]);
	}
	public function update(Request $request,Owner $owner){
		
		//Owner::update($request->all());
		$owner = Owner::find($owner->id);
		$owner->name=$request->name;
		$owner->mobile=$request->mobile;
		$owner->email=$request->email;
		$owner->address=$request->address;
		if(isset($request->photo)){
			$owner->photo=$request->photo;
		}
date_default_timezone_set("Asia/Dhaka");
		$owner->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$owner->updated_at=date('Y-m-d H:i:s');

		$owner->save();
		if(isset($request->photo)){
			$imageName=$owner->id.'.'.$request->photo->extension();
			$owner->photo=$imageName;
			$owner->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return redirect()->route("owners.index")->with('success','Updated Successfully.');
	}
	public function destroy(Owner $owner){

		
		$owner->delete();
		return redirect()->route("owners.index")->with('success', 'Deleted Successfully.');
	}
}
?>
