<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_ProjectPlansDetaileController.php" was generated by ProBot AI.
* Date: 4/14/2023 2:32:55 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\ProjectPlansDetaile;
use App\Models\Employee;
use App\Models\Material;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class ProjectPlansDetaileController extends Controller{
	public function index(){

		

		$projectplansdetailes = ProjectPlansDetaile::paginate(10);
		return view("pages.erp.projectplansdetaile.index",["projectplansdetailes"=>$projectplansdetailes]);
	}
	public function create(){

		

		return view("pages.erp.projectplansdetaile.create",["employees"=>Employee::all(),"materials"=>Material::all()]);
	}
	public function store(Request $request){
		

		//ProjectPlansDetaile::create($request->all());
		$projectplansdetaile = new ProjectPlansDetaile;
		$projectplansdetaile->employee_id=$request->employee_id;
		$projectplansdetaile->designation=$request->designation;
		$projectplansdetaile->task_id=$request->task_id;
		$projectplansdetaile->material_id=$request->material_id;
		$projectplansdetaile->brand=$request->brand;
date_default_timezone_set("Asia/Dhaka");
		$projectplansdetaile->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$projectplansdetaile->updated_at=date('Y-m-d H:i:s');

		$projectplansdetaile->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){

		

		$projectplansdetaile = ProjectPlansDetaile::find($id);
		return view("pages.erp.projectplansdetaile.show",["projectplansdetaile"=>$projectplansdetaile]);
	}
	public function edit(ProjectPlansDetaile $projectplansdetaile){
		return view("pages.erp.projectplansdetaile.edit",["projectplansdetaile"=>$projectplansdetaile,"employees"=>Employee::all(),"materials"=>Material::all()]);
	}
	public function update(Request $request,ProjectPlansDetaile $projectplansdetaile){
		
		//ProjectPlansDetaile::update($request->all());
		$projectplansdetaile = ProjectPlansDetaile::find($projectplansdetaile->id);
		$projectplansdetaile->employee_id=$request->employee_id;
		$projectplansdetaile->designation=$request->designation;
		$projectplansdetaile->task_id=$request->task_id;
		$projectplansdetaile->material_id=$request->material_id;
		$projectplansdetaile->brand=$request->brand;
date_default_timezone_set("Asia/Dhaka");
		$projectplansdetaile->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$projectplansdetaile->updated_at=date('Y-m-d H:i:s');

		$projectplansdetaile->save();

		return redirect()->route("projectplansdetailes.index")->with('success','Updated Successfully.');
	}
	public function destroy(ProjectPlansDetaile $projectplansdetaile){
		
		$projectplansdetaile->delete();
		return redirect()->route("projectplansdetailes.index")->with('success', 'Deleted Successfully.');
	}
}
?>
