<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_ProjectPlanController.php" was generated by ProBot AI.
* Date: 4/9/2023 12:19:58 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\ProjectPlan;
use App\Models\Project;
use App\Models\Task;
use App\Models\Material;
use App\Models\Employee;
use App\Models\Designation;
use App\Models\EmployeeDesignation;
use App\Models\ProjectPlansDetaile;
use App\Models\ProjectTask;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class ProjectPlanController extends Controller{
	public function index(){

		

		$projectplans = DB::table("project_plans as l")
		->join("projects as p","l.project_id","=","p.id")
		->select("l.*","p.name as pname")
		->paginate(5);
		return view("pages.erp.projectplan.index",["projectplans"=>$projectplans]);
	}
	public function create(){
		

		return view("pages.erp.projectplan.create",["projects"=>Project::all(),"tasks"=>ProjectTask::all(),"materials"=>Material::all(),"employees"=>Employee::all(),"designations"=>EmployeeDesignation::all()]);
	}
	public function store(Request $request){

		


		//   return $request->cmbProject;
		// ProjectPlan::create($request->all());

		$projectplan = new ProjectPlan;

		$projectplan->project_id=$request->cmbProject;		
		$projectplan->start=date("Y-m-d",strtotime($request->txtStartTime));
		$projectplan->end=date("Y-m-d",strtotime($request->txtEndTime));



		$projectplan->save();


		 $detailplans=$request->txtplans;

		 foreach($detailplans as $detailplan){

			$plandetails=new ProjectPlansDetaile;

				$plandetails->plan_id=$projectplan->id;
				$plandetails->employee_id=$detailplan['item_id'];
				$plandetails->designation_id=$detailplan['designation'];
				$plandetails->task_id=$detailplan['t_id'];
				$plandetails->material_id=$detailplan['m_id'];
				$plandetails->brand=$detailplan['brand'];

				$plandetails->save();
		 }
		
		

		

		return back()->with('success', 'Created Successfully.');
	}


	public function show($id){

		

		$projectplan = ProjectPlan::find($id);
		$project=Project::find($projectplan->project_id);

		$plandetails=DB::table("project_plans_detailes")
		->where("plan_id",$id)
		->get();

		$plandetails=DB::table("project_plans_detailes as p")
		->join("employees as e","p.employee_id","=","e.id")
		->join("employee_designations as d","p.designation_id","=","d.id")
		->join("project_tasks as t","p.task_id","=","t.id")
		->join("materials as m","p.material_id","=","m.id")
		->where("p.plan_id",$id)
		->select("p.*","e.name as employee","d.name as designation","t.name as task","m.name as material")
		->get();
		return view("pages.erp.projectplan.show",["projectplan"=>$projectplan,"project"=>$project,"plandetails"=>$plandetails]);
	}
	public function edit(ProjectPlan $projectplan){
		

		return view("pages.erp.projectplan.edit",["projectplan"=>$projectplan,"projects"=>Project::all(),"tasks"=>ProjectTask::all(),"materials"=>Material::all(),"employees"=>Employee::all(),"designations"=>EmployeeDesignation::all()]);
	}
	public function update(Request $request,ProjectPlan $projectplan){

		
		//ProjectPlan::update($request->all());
		$projectplan = ProjectPlan::find($projectplan->id);
		$projectplan->project_id=$request->project_id;		
		$projectplan->start=$request->start;
		$projectplan->end=$request->end;
date_default_timezone_set("Asia/Dhaka");
		$projectplan->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$projectplan->updated_at=date('Y-m-d H:i:s');

		$projectplan->save();

		return redirect()->route("projectplans.index")->with('success','Updated Successfully.');
	}
	public function destroy(ProjectPlan $projectplan){

		
		$projectplan->delete();
		return redirect()->route("projectplans.index")->with('success', 'Deleted Successfully.');
	}

	public function get_projectplan_json(){

		$sess_id=session('sess_id');
   if(isset($sess_id))return redirect('/');
		$id=$_GET("id");
		$request=ProjectPlan::find($id);
		return json_decode($request);
	}
}
?>
