<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_ProjectTaskController.php" was generated by ProBot AI.
* Date: 4/3/2023 1:23:34 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\ProjectTask;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class ProjectTaskController extends Controller{
	public function index(){
		
		$projecttasks = ProjectTask::paginate(5);
		return view("pages.erp.projecttask.index",["projecttasks"=>$projecttasks]);
	}
	public function create(){
		return view("pages.erp.projecttask.create");
	}
	public function store(Request $request){
		//ProjectTask::create($request->all());
		$projecttask = new ProjectTask;
		$projecttask->name=$request->name;

		$projecttask->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$projecttask = ProjectTask::find($id);
		return view("pages.erp.projecttask.show",["projecttask"=>$projecttask]);
	}
	public function edit(ProjectTask $projecttask){
		return view("pages.erp.projecttask.edit",["projecttask"=>$projecttask,]);
	}
	public function update(Request $request,ProjectTask $projecttask){
		//ProjectTask::update($request->all());
		$projecttask = ProjectTask::find($projecttask->id);
		$projecttask->name=$request->name;

		$projecttask->save();

		return redirect()->route("projecttasks.index")->with('success','Updated Successfully.');
	}
	public function destroy(ProjectTask $projecttask){
		
		$projecttask->delete();
		return redirect()->route("projecttasks.index")->with('success', 'Deleted Successfully.');
	}
}
?>
