<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PurchaseDetailController.php" was generated by ProBot AI.
* Date: 4/15/2023 12:11:35 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\PurchaseDetail;
use App\Models\Purchase;
use App\Models\Material;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PurchaseDetailController extends Controller{
	public function index(){
		$purchasedetails = PurchaseDetail::paginate(10);
		return view("pages.erp.purchasedetail.index",["purchasedetails"=>$purchasedetails]);
	}
	public function create(){
		return view("pages.erp.purchasedetail.create",["purchases"=>Purchase::all(),"materials"=>Material::all()]);
	}
	public function store(Request $request){
		//PurchaseDetail::create($request->all());
		$purchasedetail = new PurchaseDetail;
		$purchasedetail->purchase_id=$request->purchase_id;
		$purchasedetail->material_id=$request->material_id;
		$purchasedetail->qty=$request->qty;
		$purchasedetail->price=$request->price;
		$purchasedetail->vat=$request->vat;
		$purchasedetail->discount=$request->discount;

		$purchasedetail->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$purchasedetail = PurchaseDetail::find($id);
		return view("pages.erp.purchasedetail.show",["purchasedetail"=>$purchasedetail]);
	}
	public function edit(PurchaseDetail $purchasedetail){
		return view("pages.erp.purchasedetail.edit",["purchasedetail"=>$purchasedetail,"purchases"=>Purchase::all(),"materials"=>Material::all()]);
	}
	public function update(Request $request,PurchaseDetail $purchasedetail){
		//PurchaseDetail::update($request->all());
		$purchasedetail = PurchaseDetail::find($purchasedetail->id);
		$purchasedetail->purchase_id=$request->purchase_id;
		$purchasedetail->material_id=$request->material_id;
		$purchasedetail->qty=$request->qty;
		$purchasedetail->price=$request->price;
		$purchasedetail->vat=$request->vat;
		$purchasedetail->discount=$request->discount;

		$purchasedetail->save();

		return redirect()->route("purchasedetails.index")->with('success','Updated Successfully.');
	}
	public function destroy(PurchaseDetail $purchasedetail){
		$purchasedetail->delete();
		return redirect()->route("purchasedetails.index")->with('success', 'Deleted Successfully.');
	}
}
?>
