<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_RequisitionDetaileController.php" was generated by ProBot AI.
* Date: 4/8/2023 1:58:30 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\RequisitionDetaile;
use App\Models\Requisition;
use App\Models\Project;
use App\Models\Project_Task;
use App\Models\Material;
use App\Models\ProjectTask;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class RequisitionDetaileController extends Controller{
	public function index(){
		$requisitiondetailes = RequisitionDetaile::paginate(10);
		return view("pages.erp.requisitiondetaile.index",["requisitiondetailes"=>$requisitiondetailes]);
	}
	public function create(){
		return view("pages.erp.requisitiondetaile.create",["requisitions"=>Requisition::all(),"projects"=>Project::all(),"project_tasks"=>ProjectTask::all(),"materials"=>Material::all()]);
	}
	public function store(Request $request){
		//RequisitionDetaile::create($request->all());
		$requisitiondetaile = new RequisitionDetaile;
		$requisitiondetaile->requisition_id=$request->requisition_id;
		$requisitiondetaile->project_id=$request->project_id;
		$requisitiondetaile->project_task_id=$request->project_task_id;
		$requisitiondetaile->material_id=$request->material_id;
		$requisitiondetaile->qty=$request->qty;
date_default_timezone_set("Asia/Dhaka");
		$requisitiondetaile->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$requisitiondetaile->updated_at=date('Y-m-d H:i:s');

		$requisitiondetaile->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$requisitiondetaile = RequisitionDetaile::find($id);
		return view("pages.erp.requisitiondetaile.show",["requisitiondetaile"=>$requisitiondetaile]);
	}
	public function edit(RequisitionDetaile $requisitiondetaile){
		return view("pages.erp.requisitiondetaile.edit",["requisitiondetaile"=>$requisitiondetaile,"requisitions"=>Requisition::all(),"projects"=>Project::all(),"project_tasks"=>ProjectTask::all(),"materials"=>Material::all()]);
	}
	public function update(Request $request,RequisitionDetaile $requisitiondetaile){
		//RequisitionDetaile::update($request->all());
		$requisitiondetaile = RequisitionDetaile::find($requisitiondetaile->id);
		$requisitiondetaile->requisition_id=$request->requisition_id;
		$requisitiondetaile->project_id=$request->project_id;
		$requisitiondetaile->project_task_id=$request->project_task_id;
		$requisitiondetaile->material_id=$request->material_id;
		$requisitiondetaile->qty=$request->qty;
date_default_timezone_set("Asia/Dhaka");
		$requisitiondetaile->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$requisitiondetaile->updated_at=date('Y-m-d H:i:s');

		$requisitiondetaile->save();

		return redirect()->route("requisitiondetailes.index")->with('success','Updated Successfully.');
	}
	public function destroy(RequisitionDetaile $requisitiondetaile){
		$requisitiondetaile->delete();
		return redirect()->route("requisitiondetailes.index")->with('success', 'Deleted Successfully.');
	}
}
?>
