<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_StockController.php" was generated by ProBot AI.
* Date: 4/15/2023 11:42:38 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Stock;
use App\Models\Material;
use App\Models\Uom;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class StockController extends Controller{
	public function index(){
		$stocks = DB::table("stocks as s")
		->join("materials as m","s.material_id","=","m.id")
		->join("uoms as u","s.uom_id","=","u.id")
		->select("s.id","m.name as material","s.qty","u.name as uom","s.created_at","s.updated_at")
		->paginate(5);
		return view("pages.erp.stock.index",["stocks"=>$stocks]);
	}
	public function create(){
		return view("pages.erp.stock.create",["materials"=>Material::all(),"uom"=>Uom::all()]);
	}
	public function store(Request $request){
		//Stock::create($request->all());
		$stock = new Stock;
		$stock->material_id=$request->material_id;
		$stock->qty=$request->qty;
		$stock->uom_id=$request->uom_id;
		$stock->status=$request->status;
date_default_timezone_set("Asia/Dhaka");
		$stock->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$stock->updated_at=date('Y-m-d H:i:s');

		$stock->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		// $stock = Stock::find($id);
		// $stocks = DB::table('stocks as s')
		$stock = Stock::find($id);
		$stock_details = DB::table('materials')
    	->join('stocks', 'stocks.material_id', '=', 'materials.id')
		->join('uoms','stocks.uom_id','=','uoms.id')
    	->select('stocks.*', 'materials.name as material_name','uoms.name as uom_name')
    	->where('stocks.id', '=', $id)
    	->get();
        // ->join('materials as m', 'm.id', '=', 's.material_id')
		// ->join('uoms as u','u.id','=','s.uom_id')
        // ->select('s.id as sid', 'm.id', 'm.name as mname','u.id','u.name as uname', DB::raw('SUM(s.qty) as stock'))
        // ->groupBy('s.material_id')
        // ->get();
		return view("pages.erp.stock.show",["stock"=>$stock,"stock_details"=>$stock_details]);
	}
	public function edit(Stock $stock){
		return view("pages.erp.stock.edit",["stock"=>$stock,"materials"=>Material::all(),"uom"=>Uom::all()]);
	}
	public function update(Request $request,Stock $stock){
		//Stock::update($request->all());
		$stock = Stock::find($stock->id);
		$stock->material_id=$request->material_id;
		$stock->qty=$request->qty;
		$stock->uom_id=$request->uom_id;
		$stock->status=$request->status;
date_default_timezone_set("Asia/Dhaka");
		$stock->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$stock->updated_at=date('Y-m-d H:i:s');

		$stock->save();

		return redirect()->route("stocks.index")->with('success','Updated Successfully.');
	}
	public function destroy(Stock $stock){
		$stock->delete();
		return redirect()->route("stocks.index")->with('success', 'Deleted Successfully.');
	}

	// public function report(){
	// 	$materials=DB::table('stock_view')
	// 			->select('stock_view.*',DB::raw('SUM(total_qty) AS total_qty'))
	// 			->groupBy('name')
	// 			->get();
				

	// 			return view('pages.erp.stock.report',["materials"=>$materials]);
	// }

	public function report(){

		$products=DB::table('stock_view')
		->select('name','total_qty',DB::raw('SUM(total_qty) as total_qty'))
		->groupBy('name')
		->get();

		
		return view('pages.erp.stock.report',["products"=>$products]);
	}
}
?>
<!-- CREATE VIEW lr_stock_view AS
SELECT lr_materials.name,lr_stocks.qty AS total_qty
FROM lr_materials
JOIN lr_stocks ON lr_materials.id=lr_stocks.material_id; -->