<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_TimesheetController.php" was generated by ProBot AI.
* Date: 4/4/2023 11:31:07 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Timesheet;
use App\Models\Project;
use App\Models\Project_Task;
use App\Models\Client;
use App\Models\Department;
use App\Models\Employee;
use App\Models\ProjectTask;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class TimesheetController extends Controller{
	public function index(){
		// $timesheets = Timesheet::paginate(10);
		$timesheets=DB::table("timesheets as t")

		->join("projects as p","t.project_id","=","p.id")
        ->join("project_tasks as k","t.project_task_id","=","k.id")
        ->join("departments as d","t.department_id","=","d.id")
		->join("clients as c","t.client_id","=","c.id")
		->join("employees as e","t.employee_id","=","e.id")
		
		
        ->select("t.id","p.name as pro","k.name as ptask","d.name as department","c.name as clien","e.name as em","t.start_time","t.end_time","t.breack_hour","t.regular_hour","t.overtime_hour","t.sick_hour","t.total_hour","t.created_at","t.updated_at")		
        
		->paginate(5);
		return view("pages.erp.timesheet.index",["timesheets"=>$timesheets]);
	}
	public function create(){
		return view("pages.erp.timesheet.create",["projects"=>Project::all(),"project_tasks"=>ProjectTask::all(),"clients"=>Client::all(),"employees"=>Employee::all(),"departments"=>Department::all()]);
	}
	public function store(Request $request){
		//Timesheet::create($request->all());
		$timesheet = new Timesheet;
		$timesheet->project_id=$request->project_id;
		$timesheet->project_task_id=$request->project_task_id;
		$timesheet->department_id=$request->department_id;
		$timesheet->client_id=$request->client_id;
		$timesheet->employee_id=$request->employee_id;
		$timesheet->start_time=$request->start_time;
		$timesheet->end_time=$request->end_time;
		$timesheet->breack_hour=$request->breack_hour;
		$timesheet->regular_hour=$request->regular_hour;
		$timesheet->overtime_hour=$request->overtime_hour;
		$timesheet->sick_hour=$request->sick_hour;
		
date_default_timezone_set("Asia/Dhaka");
		$timesheet->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$timesheet->updated_at=date('Y-m-d H:i:s');

		$timesheet->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$timesheet = Timesheet::find($id);
		$employees=Employee::find($timesheet->employee_id);
		
		$timesheet=DB::table("timesheets as t")

		->join("projects as p","t.project_id","=","p.id")
        ->join("project_tasks as k","t.project_task_id","=","k.id")
		->join("departments as d","t.department_id","=","d.id")
		->join("clients as c","t.client_id","=","c.id")
		->join("employees as e","t.employee_id","=","e.id")
		->where("t.id",$id)		
        ->select("t.id","p.name as pro","k.name as ptask","d.name as department","c.name as clien","e.name as em","t.start_time","t.end_time","t.breack_hour","t.regular_hour","t.overtime_hour","t.sick_hour","t.total_hour","t.created_at","t.updated_at")		
        ->first();
		
		return view("pages.erp.timesheet.show",["timesheet"=>$timesheet,"employee"=>$employees]);
	}
	public function edit(Timesheet $timesheet){
		return view("pages.erp.timesheet.edit",["timesheet"=>$timesheet,"projects"=>Project::all(),"project_tasks"=>ProjectTask::all(),"clients"=>Client::all(),"employees"=>Employee::all(),"departments"=>Department::all()]);
	}
	public function update(Request $request,Timesheet $timesheet){
		//Timesheet::update($request->all());
		$timesheet = Timesheet::find($timesheet->id);
		$timesheet->project_id=$request->project_id;
		$timesheet->project_task_id=$request->project_task_id;
		$timesheet->department_id=$request->department_id;
		$timesheet->client_id=$request->client_id;
		$timesheet->employee_id=$request->employee_id;
		$timesheet->start_time=$request->start_time;
		$timesheet->end_time=$request->end_time;
		$timesheet->breack_hour=$request->breack_hour;
		$timesheet->regular_hour=$request->regular_hour;
		$timesheet->overtime_hour=$request->overtime_hour;
		$timesheet->sick_hour=$request->sick_hour;
		$timesheet->total_hour=$request->total_hour;
date_default_timezone_set("Asia/Dhaka");
		$timesheet->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$timesheet->updated_at=date('Y-m-d H:i:s');

		$timesheet->save();

		return redirect()->route("timesheets.index")->with('success','Updated Successfully.');
	}
	public function destroy(Timesheet $timesheet){
		$timesheet->delete();
		return redirect()->route("timesheets.index")->with('success', 'Deleted Successfully.');
	}
}
?>
