<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_TimesheetController.php" was generated by ProBot AI.
* Date: 5/15/2023 9:08:06 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Timesheet;
use App\Models\Project;
use App\Models\Project_Task;
use App\Models\Department;
use App\Models\Client;
use App\Models\Employee;
use App\Models\ProjectTask;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;

class TimesheetController extends Controller{
	public function index(){
		$timesheets=DB::table("timesheets as t")

		->join("projects as p","t.project_id","=","p.id")
        ->join("project_tasks as k","t.project_task_id","=","k.id")
        ->join("departments as d","t.department_id","=","d.id")
		->join("clients as c","t.client_id","=","c.id")
		->join("employees as e","t.employee_id","=","e.id")
		->select("t.*","p.name as pro","k.name as ptask","d.name as department","c.name as clien","e.name as em")
		->paginate(5);

		
		return view("pages.erp.timesheet.index",["timesheets"=>$timesheets]);
	}
	public function create(){
		return view("pages.erp.timesheet.create",["projects"=>Project::all(),"project_tasks"=>ProjectTask::all(),"departments"=>Department::all(),"clients"=>Client::all(),"employees"=>Employee::all()]);
	}
	public function store(Request $request){
		//Timesheet::create($request->all());
		$timesheet = new Timesheet;
		$timesheet->project_id=$request->project_id;
		$timesheet->project_task_id=$request->project_task_id;
		$timesheet->department_id=$request->department_id;
		$timesheet->client_id=$request->client_id;
		$timesheet->employee_id=$request->employee_id;
		$timesheet->start_times=$request->start_times;
		$timesheet->end_times=$request->end_times;
		$timesheet->break_hours=$request->break_hours;
		$timesheet->regular_hours=$request->regular_hours;
		$timesheet->overtime_hours=$request->overtime_hours;
		$timesheet->sick_days=$request->txtsickdays ? 1 : 0;
		$timesheet->ispresent=$request->txtPresent ? 1 : 0;
		$timesheet->date=date("Y-m-d",strtotime($request->txtDate));
		
date_default_timezone_set("Asia/Dhaka");
		$timesheet->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$timesheet->updated_at=date('Y-m-d H:i:s');

		$timesheet->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){


		// $workDaysCount = Timesheet::where('employee_id', $employeeId)
		// ->whereYear('date', $year)
		// ->whereMonth('date', $month)
		// ->where('ispresent', 1)
		// ->count();

		$timesheet = Timesheet::find($id);
		$employees=Employee::find($timesheet->employee_id);
		
		$timesheet=DB::table("timesheets as t")

		->join("projects as p","t.project_id","=","p.id")
        ->join("project_tasks as k","t.project_task_id","=","k.id")
		->join("departments as d","t.department_id","=","d.id")
		->join("clients as c","t.client_id","=","c.id")
		->join("employees as e","t.employee_id","=","e.id")
		->where("t.id",$id)
		->select("t.*","p.name as pro","k.name as ptask","d.name as department","c.name as clien","e.name as em")
		->first();		


		return view("pages.erp.timesheet.show",["timesheet"=>$timesheet,"employee"=>$employees]);
	}
	public function edit(Timesheet $timesheet){
		return view("pages.erp.timesheet.edit",["timesheet"=>$timesheet,"projects"=>Project::all(),"project_tasks"=>ProjectTask::all(),"departments"=>Department::all(),"clients"=>Client::all(),"employees"=>Employee::all()]);
	}
	public function update(Request $request,Timesheet $timesheet){
		//Timesheet::update($request->all());
		$timesheet = Timesheet::find($timesheet->id);
		$timesheet->project_id=$request->project_id;
		$timesheet->project_task_id=$request->project_task_id;
		$timesheet->department_id=$request->department_id;
		$timesheet->client_id=$request->client_id;
		$timesheet->employee_id=$request->employee_id;
		$timesheet->start_times=$request->start_times;
		$timesheet->end_times=$request->end_times;
		$timesheet->break_hours=$request->break_hours;
		$timesheet->regular_hours=$request->regular_hours;
		$timesheet->overtime_hours=$request->overtime_hours;
		$timesheet->sick_days=$request->txtsickdays ? 1 : 0;
		$timesheet->ispresent=$request->txtPresent ? 1 : 0;
		$timesheet->date=date("Y-m-d",strtotime($request->txtDate));

		
date_default_timezone_set("Asia/Dhaka");
		$timesheet->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$timesheet->updated_at=date('Y-m-d H:i:s');

		$timesheet->save();

		return redirect()->route("timesheets.index")->with('success','Updated Successfully.');
	}
	public function destroy(Timesheet $timesheet){
		$timesheet->delete();
		return redirect()->route("timesheets.index")->with('success', 'Deleted Successfully.');
	}
}
?>
