<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_WarehouseController.php" was generated by ProBot AI.
* Date: 4/7/2023 2:36:09 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Warehouse;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class WarehouseController extends Controller{
	public function index(){
		$warehouses = Warehouse::paginate(5);
		return view("pages.erp.warehouse.index",["warehouses"=>$warehouses]);
	}
	public function create(){
		return view("pages.erp.warehouse.create",[]);
	}
	public function store(Request $request){
		//Warehouse::create($request->all());
		$warehouse = new Warehouse;
		$warehouse->name=$request->name;
		$warehouse->city=$request->city;
		$warehouse->mobile=$request->mobile;

		$warehouse->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$warehouse = Warehouse::find($id);
		return view("pages.erp.warehouse.show",["warehouse"=>$warehouse]);
	}
	public function edit(Warehouse $warehouse){
		return view("pages.erp.warehouse.edit",["warehouse"=>$warehouse,]);
	}
	public function update(Request $request,Warehouse $warehouse){
		//Warehouse::update($request->all());
		$warehouse = Warehouse::find($warehouse->id);
		$warehouse->name=$request->name;
		$warehouse->city=$request->city;
		$warehouse->mobile=$request->mobile;

		$warehouse->save();

		return redirect()->route("warehouses.index")->with('success','Updated Successfully.');
	}
	public function destroy(Warehouse $warehouse){
		$warehouse->delete();
		return redirect()->route("warehouses.index")->with('success', 'Deleted Successfully.');
	}

	public function get_warehouse_json(){
        $id=$_GET["id"];     
        $request=Warehouse::find($id);
		
         return json_encode($request);
     }
}
?>
